# Generated by Django 5.1.4 on 2026-01-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='trainer',
        ),
    ]
