# Generated by Django 5.1.4 on 2026-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_certificate_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reminder_expired_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reminder_soon_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
