# Generated by Django 5.1.4 on 2026-01-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificate_issue_date'),
        ('certificate', '0005_certificate_reminder_expired_sent_and_more'),
    ]

    operations = [
    ]
