# Generated by Django 6.0 on 2026-01-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_merge_20260109_1339'),
        ('certificate', '0006_merge_20260110_0954'),
    ]

    operations = [
    ]
