# Generated by Django 5.1.4 on 2026-01-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_merge_20260109_1339'),
        ('certificate', '0006_merge_20260110_0954'),
    ]

    operations = [
    ]
