# Generated by Django 6.0 on 2025-12-27 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('qr_code_data', models.TextField(blank=True, null=True, verbose_name='Scanned QR code data')),
                ('qr_scan_time', models.DateTimeField(blank=True, null=True, verbose_name='QR code scan time')),
                ('is_qr_used', models.BooleanField(default=False, verbose_name='QR code already used')),
                ('user_id', models.UUIDField()),
                ('training_id', models.UUIDField()),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('user_id', 'training_id')},
            },
        ),
    ]
