# Generated by Django 6.0 on 2025-12-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='training_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
