# Generated by Django 6.0 on 2025-12-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in_time']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_qr_used',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='qr_scan_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='recorded_by',
        ),
    ]
