# Generated by Django 5.1.4 on 2025-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_created_at_alter_training_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='cpd_points',
            field=models.IntegerField(default=0),
        ),
    ]
