# Generated by Django 6.0 on 2026-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_cpd_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='complete_status',
            field=models.CharField(choices=[('Not Completed', 'Not Completed'), ('Completed', 'Completed')], default='Not Completed', max_length=15),
        ),
    ]
