# Generated by Django 6.0 on 2026-01-04 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('training', '0004_trainingregistration_complete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='training',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
