# Generated by Django 6.0 on 2025-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Trainer', 'Trainer'), ('HOD', 'HOD')], default='Employee', max_length=20),
            preserve_default=False,
        ),
    ]
