# Generated by Django 6.0 on 2026-01-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Trainer', 'Trainer'), ('HOD', 'HOD')], max_length=20, null=True),
        ),
    ]
