# Generated by Django 6.0 on 2026-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Trainer', 'Trainer'), ('HOD', 'HOD'), ('HR', 'HR')], default='Employee', max_length=20),
        ),
    ]
